name: Check URLs
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: URLs-checker
        uses: SuperKogito/URLs-checker@0.1.2
        with:
          # The project base path.
          git_path: https://github.com/davidosomething/20.davidosomething.com

          # A comma-separated list of file types to cover in the URL checks
          file_types: .md

          # Choose whether to include file with no URLs in the prints.
          print_all: false
